spring:
  application:
    name: stars
  datasource:
    url: jdbc:postgresql://localhost:5432/stars_db
    username: stars_user
    password: stars_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 500
        order_inserts: true
        order_updates: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: stars-events-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: com.stars.domain.entities
        spring.json.value.default.type: com.stars.domain.entities.UserEntity
        max.poll.records: 500
        batch-size: 500
        max-wait-ms: 200

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      max.block.ms: 5000
      request.timeout.ms: 5000
      delivery.timeout.ms: 15000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
